export declare const POOL_SWITCHING_FAILURE_PREFIX = "[Error - Pool Switching]";
export declare const POOL_VERIFICATION_FAILURE_PREFIX = "[Error - Pool Verification]";
export declare const MINER_HASHRATE_FAILURE_PREFIX = "[Error - HashRate]";
export declare const MINER_FAN_SPEED_FAILURE_PREFIX = "[Error - Fan Speed]";
export declare const MINER_TEMPERATURE_FAILURE_PREFIX = "[Error - Temperature]";
export declare const POOL_STATUS_HEALTHY_MSG = "Healthy Pool Status";
export declare const MINER_HASHRATE_HEALTHY_MSG = "Healthy Hashrate";
export declare const MINER_FAN_SPEED_HEALTHY_MSG = "Healthy Fan Speed";
export declare const MINER_TEMPERATURE_HEALTHY_MSG = "Healthy Temperatures";
export declare const MINER_ONLINE_HEALTHY_MSG = "Miner is Reachable";
//# sourceMappingURL=constants.d.ts.map